{% set name = "ariadne" %}
{% set version = "0.26.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ariadne-{{ version }}.tar.gz
  sha256: 27129338d21419300232dd163498ab1d7c92c02a14a2061af618a913f02f3722

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - hatchling
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - graphql-core >=3.2.0,<3.2.6
    - starlette >0.17,<1.0
    - typing_extensions >=3.6.0

test:
  imports:
    - ariadne
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://ariadnegraphql.org/
  dev_url: https://github.com/mirumee/ariadne
  doc_url: https://ariadnegraphql.org/docs/intro
  summary: Ariadne is a Python library for implementing GraphQL servers.
  license: BSD-3-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
