schema_version: 1

context:
  name: ariadne
  version: 0.26.2

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/ariadne-${{ version }}.tar.gz
  sha256: 607617f82760c039b2137b7c1200b475ea90ccf4ca42c0994926c0d8fdede908

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - hatchling
    - pip
    - python ${{ python_min }}.*
  run:
    - python >=${{ python_min }}
    - graphql-core >=3.2.0,<3.2.6
    - starlette >0.17,<1.0
    - typing_extensions >=3.6.0

tests:
  - python:
      imports:
        - ariadne
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Ariadne is a Python library for implementing GraphQL servers.
  license: BSD-3-Clause
  license_file:
    - LICENSE
  homepage: https://ariadnegraphql.org/
  repository: https://github.com/mirumee/ariadne
  documentation: https://ariadnegraphql.org/docs/intro

extra:
  recipe-maintainers:
    - thewchan
